DROP TABLE IF EXISTS weight;

CREATE TABLE weight (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  datetime INTEGER,
  weight REAL
);

DROP TABLE IF EXISTS auth_tokens;

CREATE TABLE auth_token (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  token TEXT UNIQUE
);
